### ISSUE TITLE
Permission Denied while ```vagrant ssh```

### ISSUE THREAD

**Issue by sugamkarki** [oracle/vagrant-projects#356] opened 2021-03-23 13:13 UTC
![image](https://user-images.githubusercontent.com/51502114/112151745-abcf0e80-8c09-11eb-975f-3961f62063bc.png)
This error is consistent even if I open up powershell/command prompt with administrator privileges. Although I can connect to the database from SQL developer. I want to have access to the sqlplus if possible.

**Comment by PaulNeumann** [comment] 2021-03-23 15:20
@sugamkarki Some Windows patches can cause this error. By default, Vagrant uses the ssh client provided by Windows, and some versions of the Windows ssh client don't work well with Vagrant. To see whether this is the problem, please try running the following from a Command Prompt (it doesn't need to have Administrator privileges):

```batch
SET VAGRANT_PREFER_SYSTEM_BIN=0
vagrant ssh
```

The environment variable tells Vagrant to use its own ssh client, instead of the Windows ssh client. If `vagrant ssh` then works, the problem is likely due to a Windows patch, and you can use the environment variable as a workaround.

**Comment by sugamkarki** [comment] 2021-03-23 17:17
@PaulNeumann I tried the way you suggested but the problem still persists.

**Comment by PaulNeumann** [comment] 2021-03-23 22:08
@sugamkarki Could you please post the output of the `vagrant ssh-config` command? Please make sure the VM is running before running the command.

**Comment by sugamkarki** [comment] 2021-03-24 07:52
@PaulNeumann 
```
❯ vagrant ssh-config
Host oracle-19c-vagrant
  HostName 127.0.0.1
  User vagrant
  Port 2222
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile "E:/NAMI/Year 2/Term II/Assignments/Database/vagrant/vagrant-projects/OracleDatabase/19.3.0/.vagrant/machines/oracle-19c-vagrant/virtualbox/private_key"
  IdentitiesOnly yes
  LogLevel FATAL
```
---
There is another issue too. Whenever I go ```vagrant up```, it suggests me to do a vagrant provision. while running ```vagrant provision``` this happens.
![image](https://user-images.githubusercontent.com/51502114/112273921-ff8f3580-8ca5-11eb-85e0-e751e3eae7b3.png)
---
I tried the same box on a buddy of mine and his worked perfectly.

**Comment by PaulNeumann** [comment] 2021-03-25 00:46
@sugamkarki The output from `vagrant ssh-config` looks normal.

Since you're having multiple problems with the VM, rebuilding it (`vagrant destroy`, followed by `vagrant up`) probably makes sense at this point.

The issue with resolving [yum.oracle.com](https://yum.oracle.com) might have been a temporary network problem.  However, I recommend making sure that you can browse to [yum.oracle.com](https://yum.oracle.com) before rebuilding the VM. If your host computer can't connect, the VM won't be able to, either.

When you rebuild the VM, you can capture the output from `vagrant up` by running `vagrant up | Tee-Object provision.log` from a PowerShell window. Hopefully the rebuild will go smoothly, but if there are any issues, having the provisioning output is very helpful for troubleshooting.

**Comment by gvenzl** [comment] 2021-06-02 18:18
Hi @sugamkarki, did reinstalling the box solve the issue?

**Comment by gvenzl** [comment] 2021-09-03 17:29
Closed due to lack of response.

**Closed** 2021-09-03 17:29 UTC
