### ISSUE TITLE
Virtualbox

### ISSUE THREAD

**Issue by Umanoid1** [oracle/vagrant-projects#294] opened 2020-09-01 18:18 UTC
Hi, kindly I have a problem in WINDOWS10 installing a new version, in a nutshell I can no longer update Vb because the file VirtualBox-6.1.6-r137129-Win.msi, I can't find it anymore, so I can't install the new version and not even uninstall, I also made a mistake I deleted some files, folders and log files manually without solving the problem, I had never had such a problem, the .MSI file downloaded by you, and not it I find more if you can kindly help me to find the .MSI file or give me a solution, in the faq I have not found the solution.

**Comment by AmedeeBulle** [comment] 2020-09-08 10:17
Closing -- duplicate of #293

**Closed by AmedeeBulle** 2020-09-08 10:17 UTC
Labels: duplicate
