### ISSUE TITLE
The initial provision failed to "Create the Kubernetes module for olcne-env" with error "restrict-service-externalip-ca-cert" may not be empty"

### ISSUE THREAD

**Issue by shaunxa** [oracle/vagrant-projects#345] opened 2021-02-18 01:19 UTC
**Describe the issue**

During the initial provisioning, it failed to "Create the Kubernetes module for olcne-env" with error the error below.

    master1: ===== Create the Kubernetes module for olcne-env  =====
    master1:     olcnectl module create --environment-name olcne-env --selinux enforcing --module kubernetes --name olcne-cluster --container-registry container-registry.oracle.com/olcne --nginx-image container-registry.oracle.com/olcne/nginx:1.17.7 --apiserver-advertise-address 192.168.99.101 --virtual-ip 192.168.99.99 --master-nodes 192.168.99.101:8090 --worker-nodes 192.168.99.111:8090,192.168.99.112:8090
    master1: Returned a non-zero code: 1
    master1: Last output lines:
    master1:   "restrict-service-externalip-ca-cert" may not be empty
    master1: kubernetes encountered error with restrict-service-externalip-tls-cert
    master1:   "restrict-service-externalip-tls-cert" may not be empty
    master1: kubernetes encountered error with restrict-service-externalip-tls-key
    master1:   "restrict-service-externalip-tls-key" may not be empty
    master1: See /var/tmp/cmd_KRgqZ.log for details

[vagrant@master1 ~]$ sudo cat /var/tmp/cmd_KRgqZ.log
Flag --apiserver-advertise-address has been deprecated, use the 'master-nodes' option to specify the IP of the API Server. This flag will be removed in OLCNE 1.3
Encountered errors with kubernetes
  Invalid arguments
kubernetes encountered error with restrict-service-externalip-ca-cert
  "restrict-service-externalip-ca-cert" may not be empty
kubernetes encountered error with restrict-service-externalip-tls-cert
  "restrict-service-externalip-tls-cert" may not be empty
kubernetes encountered error with restrict-service-externalip-tls-key
  "restrict-service-externalip-tls-key" may not be empty
[vagrant@master1 ~]$

**Environment (please complete the following information):**

- Host OS: [Windows 10 Pro]
Edition	Windows 10 Pro
Version	20H2
Installed on	‎2/‎17/‎2021
OS build	19042.746
Experience	Windows Feature Experience Pack 120.2212.551.0

- Vagrant version: [Vagrant 2.2.14]
- Vagrant provider:
  - For VirtualBox:
    - VirtualBox version: [Version 6.1.18 r142142 (Qt5.6.2)]
  
- Vagrant project:  [OLCNE]

**Additional information**

    master1:     firewall-cmd --reload
    master1: ===== Allow passwordless ssh between VMs =====
    master1:     mkdir /root/.ssh
    master1:     cp /vagrant/id_rsa /root/.ssh/
    master1:     cp /vagrant/id_rsa.pub /root/.ssh/authorized_keys
    master1:     eval cat /vagrant/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
    master1:     chmod 0700 /root/.ssh
    master1:     chmod 0600 /root/.ssh/authorized_keys /root/.ssh/id_rsa
    master1: ===== Removing the shared SSH keypair =====
    master1:     rm /vagrant/id_rsa /vagrant/id_rsa.pub
    master1: ===== Oracle Linux base software installation complete. =====
    master1: ===== Generate and deploy X.509 Certificates =====
    master1:     /etc/olcne/gen-certs-helper.sh --nodes 192.168.99.101,192.168.99.111,192.168.99.112 --cert-dir /etc/olcne/pki
    master1:     sed -i -e 's/^USER=.*/USER=vagrant/' /etc/olcne/pki/olcne-tranfer-certs.sh
    master1:     bash -e /etc/olcne/pki/olcne-tranfer-certs.sh
    master1: ===== Bootstrap the Oracle Linux Cloud Native Environment Platform Agent on all nodes =====
    master1:     /etc/olcne/bootstrap-olcne.sh --secret-manager-type file --olcne-node-cert-path /etc/olcne/pki/production/node.cert --olcne-ca-path /etc/olcne/pki/production/ca.cert --olcne-node-key-path /etc/olcne/pki/production/node.key --olcne-component api-server
    master1:     ssh 192.168.99.101 /etc/olcne/bootstrap-olcne.sh --secret-manager-type file --olcne-node-cert-path /etc/olcne/pki/production/node.cert --olcne-ca-path /etc/olcne/pki/production/ca.cert --olcne-node-key-path /etc/olcne/pki/production/node.key --olcne-component agent
    master1:     ssh 192.168.99.111 /etc/olcne/bootstrap-olcne.sh --secret-manager-type file --olcne-node-cert-path /etc/olcne/pki/production/node.cert --olcne-ca-path /etc/olcne/pki/production/ca.cert --olcne-node-key-path /etc/olcne/pki/production/node.key --olcne-component agent
    master1:     ssh 192.168.99.112 /etc/olcne/bootstrap-olcne.sh --secret-manager-type file --olcne-node-cert-path /etc/olcne/pki/production/node.cert --olcne-ca-path /etc/olcne/pki/production/ca.cert --olcne-node-key-path /etc/olcne/pki/production/node.key --olcne-component agent
    master1: ===== Create the Oracle Linux Cloud Native Environment: olcne-env =====
    master1:     olcnectl --api-server 127.0.0.1:8091 environment create --environment-name olcne-env --secret-manager-type file --olcne-node-cert-path /etc/olcne/pki/production/node.cert --olcne-ca-path /etc/olcne/pki/production/ca.cert --olcne-node-key-path /etc/olcne/pki/production/node.key --update-config
    master1: ===== Create the Kubernetes module for olcne-env  =====
    master1:     olcnectl module create --environment-name olcne-env --selinux enforcing --module kubernetes --name olcne-cluster --container-registry container-registry.oracle.com/olcne --nginx-image container-registry.oracle.com/olcne/nginx:1.17.7 --apiserver-advertise-address 192.168.99.101 --virtual-ip 192.168.99.99 --master-nodes 192.168.99.101:8090 --worker-nodes 192.168.99.111:8090,192.168.99.112:8090
    master1: Returned a non-zero code: 1
    master1: Last output lines:
    master1:   "restrict-service-externalip-ca-cert" may not be empty
    master1: kubernetes encountered error with restrict-service-externalip-tls-cert
    master1:   "restrict-service-externalip-tls-cert" may not be empty
    master1: kubernetes encountered error with restrict-service-externalip-tls-key
    master1:   "restrict-service-externalip-tls-key" may not be empty
    master1: See /var/tmp/cmd_KRgqZ.log for details
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

C:\zlab\git\oracle\vagrant-projects\OLCNE>vagrant ssh master1

Welcome to Oracle Linux Server release 8.3 (GNU/Linux 5.4.17-2036.102.0.2.el8uek.x86_64)

The Oracle Linux End-User License Agreement can be viewed here:

  * /usr/share/eula/eula.en_US

For additional packages, updates, documentation and community help, see:

  * https://yum.oracle.com/

Last login: Wed Feb 17 15:05:47 2021 from 10.0.2.2

[vagrant@master1 ~]$
[vagrant@master1 ~]$ sudo cat /var/tmp/cmd_KRgqZ.log
Flag --apiserver-advertise-address has been deprecated, use the 'master-nodes' option to specify the IP of the API Server. This flag will be removed in OLCNE 1.3
Encountered errors with kubernetes
  Invalid arguments
kubernetes encountered error with restrict-service-externalip-ca-cert
  "restrict-service-externalip-ca-cert" may not be empty
kubernetes encountered error with restrict-service-externalip-tls-cert
  "restrict-service-externalip-tls-cert" may not be empty
kubernetes encountered error with restrict-service-externalip-tls-key
  "restrict-service-externalip-tls-key" may not be empty
[vagrant@master1 ~]$

C:\zlab\git\oracle\vagrant-projects\OLCNE>vagrant status
Current machine states:

worker1                   running (virtualbox)
worker2                   running (virtualbox)
master1                   running (virtualbox)

This environment represents multiple VMs. The VMs are all listed
above with their current state. For more information about a specific
VM, run `vagrant status NAME`.

C:\zlab\git\oracle\vagrant-projects\OLCNE>

**Comment by Djelibeybi** [comment] 2021-02-18 02:39
This is a fantastic issue report, but I'm afraid I'm going to have to close it as a duplicate of #342 which already has a pull request attached.

But it really was an excellent report.

**Closed by Djelibeybi** 2021-02-18 02:39 UTC

**Comment by Djelibeybi** [comment] 2021-02-18 02:41
Duplicate of #342

**Comment by shaunxa** [comment] 2021-02-18 06:45
> This is a fantastic issue report, but I'm afraid I'm going to have to close it as a duplicate of #342 which already has a pull request attached.
> 
> But it really was an excellent report.

@Djelibeybi many thanks. I will looking into the details of #342. Thanks.

**Comment by shaunxa** [comment] 2021-02-18 08:11
> > This is a fantastic issue report, but I'm afraid I'm going to have to close it as a duplicate of #342 which already has a pull request attached.
> > But it really was an excellent report.
> 
> @Djelibeybi many thanks. I will looking into the details of #342. Thanks.

Fixed with the solution in #342. Thanks.
--------------------------------------------
    master1: ===== Create the Kubernetes module for olcne-env  =====
    master1:     olcnectl module create --environment-name olcne-env --selinux enforcing --module kubernetes --name olcne-cluster --container-registry container-registry.oracle.com/olcne --nginx-image container-registry.oracle.com/olcne/nginx:1.17.7 --apiserver-advertise-address 192.168.99.101 --virtual-ip 192.168.99.99 --master-nodes 192.168.99.101:8090 --worker-nodes 192.168.99.111:8090,192.168.99.112:8090 --restrict-service-externalip-ca-cert=/etc/olcne/pki/production/ca.cert --restrict-service-externalip-tls-cert=/etc/olcne/pki/production/node.cert --restrict-service-externalip-tls-key=/etc/olcne/pki/production/node.key
    master1: ===== Validate all required prerequisites are met for the Kubernetes module =====
    master1:     olcnectl module validate --environment-name olcne-env --name olcne-cluster
    master1: ===== Deploy the Kubernetes module into olcne-env (Be patient!) =====
    master1:     olcnectl module install --environment-name olcne-env --name olcne-cluster
    master1: ===== Deploying additional modules =====
    master1: ===== Copying admin.conf for vagrant user on master node(s) =====
    master1:     ssh 192.168.99.101 "      mkdir -p ~vagrant/.kube;       cp /etc/kubernetes/admin.conf ~vagrant/.kube/config;       chown -R vagrant: ~vagrant/.kube;       echo 'source <(kubectl completion bash)' >> ~vagrant/.bashrc;       echo 'alias k=kubectl' >> ~vagrant/.bashrc;       echo 'complete -F __start_kubectl k' >> ~vagrant/.bashrc;       "
    master1: ===== Starting kubectl proxy service on master nodes =====
    master1:     ssh 192.168.99.101 "        sed -i.bak 's/KUBECTL_PROXY_ARGS=--port 8001/KUBECTL_PROXY_ARGS=--port 8001 --accept-hosts=.* --address=0.0.0.0/'             /etc/systemd/system/kubectl-proxy.service.d/10-kubectl-proxy.conf         && systemctl daemon-reload         && systemctl enable --now kubectl-proxy.service     "
    master1: ===== Your Oracle Linux Cloud Native Environment is operational. =====
    master1: NAME                 STATUS   ROLES    AGE     VERSION
    master1: master1.vagrant.vm   Ready    master   4m30s   v1.18.10+3.el8
    master1: worker1.vagrant.vm   Ready    <none>   3m50s   v1.18.10+3.el8
    master1: worker2.vagrant.vm   Ready    <none>   3m34s   v1.18.10+3.el8

C:\zlab\git\oracle\vagrant-projects\OLCNE>
